import "./_reset.scss";
import "./_globals.scss";

import ContextLayoutComponent from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextLayoutComponent>{children}</ContextLayoutComponent>
      </body>
    </html>
  );
}
